name: arbore-snowflake
channels:
  - main
  - conda-forge
  - defaults
dependencies:
  - pandas=1.5.3
  - pip=23.0.1
  - pyarrow=10.0.1
  - python=3.9
  - python-dotenv=0.21.0
  - snowflake-connector-python=3.15.0
  - pip:
    - cryptography==41.0.7
    - snowflake-ingest==1.0.10